server:
  port: 9411
management:
  metrics:
    web:
      server:
        auto-time-requests: false
spring:
  application:
    name: zipkin-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/