spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
      discovery:
        enabled: true
  profiles:
    active: native
server:
  port: 8888
eureka:
  client:
    eureka-server-port: 8761
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
