spring:
  datasource:
    url: jdbc:mysql://localhost:3306/general-spring-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: snow0215
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-location: classpath:mybatis/mapper/*.xml
#
ribbon:
  hystrix:
    enable: true
  okhttp:
    enabled: true
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
